# Generated by Django 4.2.21 on 2025-05-24 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('TipoIdentificacion', models.CharField(max_length=50)),
                ('NumeroIdentificacion', models.CharField(max_length=50, unique=True)),
                ('Nacionalidad', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('EstadoCivil', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('IdSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroSolicitud', models.CharField(max_length=100)),
                ('TipoMoneda', models.CharField(max_length=10)),
                ('MontoSolicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PlazoFinanciero', models.IntegerField()),
                ('PropositoPrestamo', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=50)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('IdReferencia', models.AutoField(primary_key=True, serialize=False)),
                ('NombreApellido', models.CharField(max_length=255)),
                ('NumeroContacto', models.CharField(max_length=50)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('IdLaboral', models.AutoField(primary_key=True, serialize=False)),
                ('TipoEmpleo', models.CharField(max_length=50)),
                ('LugarTrabajo', models.CharField(max_length=255)),
                ('FechaContratacion', models.DateField()),
                ('FechaAlCorriente', models.DateField()),
                ('IngresosMensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoGarantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoDeudas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laborales', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='GastosMensuales',
            fields=[
                ('IdGastosMensuales', models.AutoField(primary_key=True, serialize=False)),
                ('Alimentacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VestimentaCalzado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Transporte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Colegiatura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('OtrosGastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GastosSalud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Telecomunicaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ServiciosAguaLuz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ServiciosCableInternet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_mensuales', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('IdDomicilio', models.AutoField(primary_key=True, serialize=False)),
                ('Direccion', models.CharField(max_length=255)),
                ('EstadoDomicilio', models.CharField(max_length=50)),
                ('MontoMensualidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Departamento', models.CharField(max_length=100)),
                ('Municipio', models.CharField(max_length=100)),
                ('Barrio', models.CharField(max_length=100)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Conyuge',
            fields=[
                ('IdConyuge', models.AutoField(primary_key=True, serialize=False)),
                ('NombreApellidos', models.CharField(max_length=255)),
                ('NumeroCedula', models.CharField(max_length=50, unique=True)),
                ('NumeroPersonasACargo', models.IntegerField()),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conyuges', to='validacion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Amortizacion',
            fields=[
                ('IdAmortizacion', models.AutoField(primary_key=True, serialize=False)),
                ('Mes', models.IntegerField()),
                ('Cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Capital', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CapitalVivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones', to='validacion.persona')),
            ],
        ),
    ]
