# Generated by Django 4.2.21 on 2025-05-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='TasaInteresAnual',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
    ]
